### ISSUE TITLE
The variable c-xref-set-this-frame-dispatch-data stores data to is not frame-local (patch attached)).

### ISSUE THREAD

**Issue by litvindev** [thoni56/c-xrefactory#10]
This bug prevents browsing in multiple Emacs frames.

[0001-c-xref-set-this-frame-dispatch-data.patch.txt](https://github.com/thoni56/c-xrefactory/files/691811/0001-c-xref-set-this-frame-dispatch-data.patch.txt)

**Comment by thoni56** [comment]
Thank you for your report! Although I am not sure what you mean by "prevents browsing in multiple Emacs frames".

Again, could you please give me a sequence of actions that exhibits the problem so that I can see the problem and ensure that your patch has been applied correctly.

Preferably in a step by step description of what you did, like so:
    - Visit a file in one buffer and frame
    - Place the cursor on a variable and press F6 to go to its definition
    - ...

Then what happened:
    - The cursor moved to the next occurrence of ...

And what you wanted:
   - The cursor should move to ...

Also include version of Emacs to ensure that it is not a discrepancy between versions.

Thanks!

**Comment by litvindev** [comment]
Scenario:
1) Point cursor to a symbol in frame A, execute `c-xref-browse-symbol` command
--> *symbol/classes* and *references* windows will appear in frame A
2) Point cursor to a symbol in frame B, execute `c-xref-browse-symbol` command
--> *symbol/classes* and *references* windows will not appear in frame B, windows in frame A will be reused

**Comment by litvindev** [comment]
Another scenario:
1) Eval `(c-xref-get-this-frame-id)` in frame A
--> 1 will be returned
2) Eval `(c-xref-get-this-frame-id)` in frame B
--> again, 1 will be returned (must be 2)

The issue presumably appeared since 'make-variable-frame-local` built-in function has become obsolete in 22.2 version.
