### ISSUE TITLE
Add GCC include directories detection (patch attached)

### ISSUE THREAD

**Issue by litvindev** [thoni56/c-xrefactory#11]
I detect GCC include directories by invoking cpp with -v option:
https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html

This also fixes issue #8 

Scenario:
1) Add a new project section to .c-xrefrc:
```
[/home/litvin/src/c-xrefactory]
  /home/litvin/src/c-xrefactory/src
  -refs /home/litvin/CXrefs/src/c-xrefactory
  -refnum=100
  -exactpositionresolve
```
2) Execute: `c-xref -create -xrefrc /home/litvin/.c-xrefrc -p /home/litvin/src/c-xrefactory -user 1 -xrefactory-II -crlfconversion -crconversion -encoding=default -exactpositionresolve -o /tmp/c-xref.log`
--->
A lot of warings in /tmp/c-xref.log:
```
<warning len=92><A HREF="file:///usr/include/unistd.h#229" len=12>unistd.h:229</A> can't open file stddef.h
...
<warning len=90><A HREF="file:///usr/include/zconf.h#427" len=11>zconf.h:427</A> can't open file stdarg.h
```

[0001-Add-GCC-include-directories-detection.patch.txt](https://github.com/thoni56/c-xrefactory/files/731312/0001-Add-GCC-include-directories-detection.patch.txt)

**Comment by thoni56** [comment]
Thanks again!

This is definitely a valuable feature to add. I have two issues:
- What if cpp isn't GCC? We want it to fail silently then, I suppose, because we don't know the format of the output, or even if it includes a search path. Or even the arguments, what if it barfs already on the command?
- What if LANG is not C or en_XX? On one of my systems the strings to match are "#include <...> sökning startar här:" and "Slut på söklistan.". We could set LANG to C just for this command, that would be somewhat portable, but might also barf and need to be handled with care.

**Comment by litvindev** [comment]
Thank you for clarifying, I've made "LANG=C" for this command and updated the patch.
You can check if command fails silenly by modifying PATH variable or by creating "cpp" symlinks.
