### ISSUE TITLE
Package for MELPA

### ISSUE THREAD

**Issue by rrthomas** [thoni56/c-xrefactory#34]
It's a lot easier for most users than el-get.

**Comment by thoni56** [comment]
I have searched the net and found no indication that MELPA can do anything but compile elisp packages. Since MELPA is a central repository of pre-built emacs packages (as I understand it), that makes sense.

I might be wrong, and please correct me if I am, but [this melpa issue](https://github.com/melpa/melpa/issues/1704) indicates that MELPA is not interested in supporting this either.

However, `c-xrefactory` relies heavily on the the c-xrefactory server which is a C program, which (obviously) needs to be built on the platform on which it will run. This requires the Emacs package manager to be able to run `make` and the like. `el-get` allows you to do that, MELPA doesn't.

Furthermore, c-xrefactory pre-analyses the headers on the target system by running a bootstrap step in the server build. This saves a lot of time parsing system header files during usage.

I think that this means that the only way to handle this is to supply a package for the systems package manager (which could handle the C build server) *and* a MELPA package (that handles the Emacs client). However, this introduces dependencies that probably would trip many users (not having the system package, or the wrong version of it, ...).

**Comment by thoni56** [comment]
[semantic-refactor](https://github.com/tuhdo/semantic-refactor) seems to be pure elisp and manage well with MELPA.

On the other hand it does not allow you to find definition/declarations of functions, macros and variables wherever they might be, local or in some obscure system header. (Only to mention one thing that makes `c-xrefactory` a different beast ;-)

**Comment by rrthomas** [comment]
Sorry, I'd forgotten about this unusual characteristic of c-xref (the C executable). ternjs has this sort of problem, but its executable is editor-independent. If it's worth packaging the C part separately you could do that and still put the Lisp in MELPA, but otherwise…

**Comment by rrthomas** [comment]
Also you're reminding me why I loved xref before, I'll try to at least install c-xref soon :)
