### ISSUE TITLE
Feature request: Extract / Inline variable refactorings

### ISSUE THREAD

**Issue by shanemd** [thoni56/c-xrefactory#72]
If would be nice to support extracting and inlining variables.

References:
https://www.refactoring.com/catalog/extractVariable.html
https://www.refactoring.com/catalog/inlineVariable.html

**Comment by thoni56** [comment]
I just added a crude "Extract variable" refactoring. Thanks for prompting me to actually try to enhance functionality, and it turned out that I have now enough knowledge to actually do that.

As there can never be an "Inline <whatever>" (opposite of Extract) due to the way `c-xrefactory` does its magic, I'm closing this issue.
